language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install .
  - pip install -r requirements-dev.txt
  - pip install orca urbansim  # extra tests run if urbansim is present
  - pip list
  - pip show choicemodels

script:
  - coverage run --source choicemodels --module pytest --verbose

after_success:
  - coverage report --show-missing
  - coveralls
